Repository DuckDuckStudio/yazicbs.github.io, pull requests merged in 2024-10, with the labels that each got.

#60 Sync changes
  Articles/Blogs.html
  Interesting/vacation_countdown/计算.js
  Interesting/vacation_countdown/计算_中.js
  Tools/Fufu_Tools/index.html
  Tools/Fufu_Tools/wiki/Dev/index.html
  zh_cn/index.html
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过, 内部任务

#61 [Auto Merge] 自动合并非分支特定修改
  Articles/Blogs.html
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 内部任务

#63 Mg & Articles/Blogs changes
  Articles/Blogs.html
  music_games/games/Orzmic/index.html
  music_games/games/Phigros/index.html
  music_games/photos/Orzmic/[Crush Alcohol]-0973016-A.png
  music_games/photos/Orzmic/[Crush Alcohol]-0981816-S.png
  music_games/photos/Orzmic/[Crush Expert (NORMAL)]-0993299-S.png
  music_games/photos/Orzmic/[Crush Keyboard]-0983928-S.png
  music_games/photos/Orzmic/[Forget me not]-0972746-A.png
  music_games/photos/Orzmic/[Orphe]-0991261-S.png
  music_games/photos/Orzmic/[The Everlasting Rain (NORMAL)]-0991752-Sp.png
  music_games/photos/Orzmic/[The Last Flower]-0990190-S.png
  music_games/photos/Orzmic/[つーく·つわんく]-0987134-S.png
  music_games/photos/Orzmic/[十拳剣 (NORMAL)]-0998212-S.png
  music_games/photos/Phigros/[ATHAZA(AT)]-0880871-A.png
  music_games/photos/Phigros/[ATHAZA(AT)]-0883717-A.png
  music_games/photos/Phigros/[Originally]-0999669-Vp.png
  music_games/photos/Phigros/[a truth seeker -Communication with Utopia will be lost-]-0964539-V.png
  music_games/photos/Phigros/[月詠に鳴る]-0975851-V.png
  zh_cn/index.html
Labels: DEV-开发分支合并, DEV-未经测试, DEV-需要注意, 等待补充

#65 [fix] 修复猜数字游戏会将非数字类型参数视为正确的情况
  zh_cn/js/games/guess_number.js
  zh_cn/js/games/simplified/guess_number.js
Labels: DEV-已完成, DEV-测试通过

#66 Sync changes
  Articles/Blogs.html
  README.md
  music_games/games/Orzmic/index.html
  music_games/games/Phigros/index.html
  music_games/photos/Orzmic/[Crush Alcohol]-0973016-A.png
  music_games/photos/Orzmic/[Crush Alcohol]-0981816-S.png
  music_games/photos/Orzmic/[Crush Expert (NORMAL)]-0993299-S.png
  music_games/photos/Orzmic/[Crush Keyboard]-0983928-S.png
  music_games/photos/Orzmic/[Forget me not]-0972746-A.png
  music_games/photos/Orzmic/[Orphe]-0991261-S.png
  music_games/photos/Orzmic/[The Everlasting Rain (NORMAL)]-0991752-Sp.png
  music_games/photos/Orzmic/[The Last Flower]-0990190-S.png
  music_games/photos/Orzmic/[つーく·つわんく]-0987134-S.png
  music_games/photos/Orzmic/[十拳剣 (NORMAL)]-0998212-S.png
  music_games/photos/Orzmic/[遗世之地]-0991171-S.png
  music_games/photos/Phigros/[ATHAZA(AT)]-0880871-A.png
  music_games/photos/Phigros/[ATHAZA(AT)]-0883717-A.png
  music_games/photos/Phigros/[Der Richter]-0910170-A.png
  music_games/photos/Phigros/[Der Richter]-0921732-S.png
  music_games/photos/Phigros/[Originally]-0999669-Vp.png
  music_games/photos/Phigros/[a truth seeker -Communication with Utopia will be lost-]-0964539-V.png
  music_games/photos/Phigros/[暗夜苏醒(REANIMATE)]-0914295-A.png
  music_games/photos/Phigros/[暗夜苏醒(REANIMATE)]-0956838-S.png
  music_games/photos/Phigros/[月詠に鳴る]-0975851-V.png
  zh_cn/index.html
  zh_cn/js/games/guess_number.js
  zh_cn/js/games/simplified/guess_number.js
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#45 feat🚀: 对于手机测试的控制台页面
  zh_cn/index.html
Labels: DEV-开发分支合并, DEV-测试错误, 新功能, 等待补充

#67 Auto Sync
  zh_cn/index.html
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#73 [Auto] Update sitemap 20241027T0935
  .github/PULL_REQUEST_TEMPLATE.md
  sitemap.xml
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 内部任务

#75 [Auto] Update sitemap 20241029T1314
  sitemap.xml
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 内部任务

#77 Sync change(s) to location branch.
  sitemap.xml
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过, 内部任务
