Repository DuckDuckStudio/yazicbs.github.io, pull requests merged in 2024-11, with the labels that each got.

#79 Interesting: 我家鸭子活了人几岁
  .gitignore
  Interesting/index.html
  Interesting/鸭子活了人几岁/index.html
  Interesting/鸭子活了人几岁/main.js
  Interesting/鸭子活了人几岁/style.css
Labels: DEV-自动检查错误, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 新功能

#83 pref: 移动设备优化
  Interesting/vacation_countdown/样式.css
  Interesting/鸭子活了人几岁/index.html
  Interesting/鸭子活了人几岁/main.js
  Interesting/鸭子活了人几岁/style.css
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#84 Update sitemap 2024/11/11 22:46
  sitemap.xml
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#86 Update Fufu Tools error doc(s)
  Tools/Fufu_Tools/wiki/error/index.html
Labels: DEV-已启用自动合并, DEV-开发分支合并

#88 pref: 优化 我家嘎嘎活了人几岁
  Interesting/鸭子活了人几岁/main.js
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#90 Sync fork
  .github/workflows/check_url_visit.yml
  .github/workflows/generate-sitemap.yml
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#87 feat: Auto update sitemap
  .action_scripts/JavaScript/check-local-paths.mjs
  .action_scripts/JavaScript/generate-sitemap.mjs
  .action_scripts/JavaScript/package.json
  .action_scripts/Python/link_checker.py
  .action_scripts/Python/requirements.txt
  .github/dependabot.yml
  .github/workflows/check-local-paths.yml
  .github/workflows/check_url_visit.yml
  .github/workflows/generate-sitemap.yml
  .gitignore
  sitemap.xml
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#94 Pref: 一些优化
  .action_scripts/JavaScript/generate-sitemap.mjs
  .github/workflows/generate-sitemap.yml
  404.html
  Articles/Blogs.html
  Articles/SereneScapes.html
  Articles/index.html
  Articles/有关考试成绩转换的分析.html
  CONTRIBUTING.md
  GenshinImpact/index.html
  Interesting/Fake Blue screen of death/index.html
  Interesting/KFCfkThurVMe50.html
  Interesting/VerificationFailure.html
  Interesting/duck_forever/index.html
  Interesting/index.html
  Interesting/鸭子活了人几岁/index.html
  LICENSE
  Tools/Blabberizer.html
  Tools/Fufu_Tools/index.html
  Tools/Fufu_Tools/minimum/index.html
  Tools/Fufu_Tools/online_tools/index.html
  Tools/Fufu_Tools/online_tools/实验性工具/水下音效/index.html
  Tools/Fufu_Tools/versions/index.html
  Tools/Fufu_Tools/wiki/Dev/index.html
  Tools/Fufu_Tools/wiki/config/index.html
  Tools/Fufu_Tools/wiki/error/index.html
  Tools/Fufu_Tools/wiki/index.html
  Tools/Fufu_Tools/wiki/online_tools/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/实验性小工具/hosts修改/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/实验性小工具/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/实验性小工具/批量添加水印/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/实验性小工具/自动化/自动按键连按/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/摩斯密码/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/进制转换/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/颜色代码展示/index.html
  Tools/Fufu_Tools/wiki/常见问题Q&A/主程序/index.html
  Tools/Fufu_Tools/wiki/常见问题Q&A/小工具/index.html
  Tools/Fufu_Tools/wiki/通用/index.html
  Tools/Fufu_Tools/分类解释/index.html
  Tools/chinese_git/index.html
  Tools/index.html
  index.html
  jp/404.html
  minecraft/index.html
  minecraft/promotion/fake.html
  minecraft/promotion/index.html
  minecraft/promotion/oak_island/index.html
  minecraft/promotion/oak_island/oak_island_farm.html
  music_games/games/Arcaea/index.html
  music_games/games/GenshinImpact/index.html
  music_games/games/MuseDash/index.html
  music_games/games/Orzmic/index.html
  music_games/games/Other/index.html
  music_games/games/Phigros/index.html
  music_games/games/Project_Sekai/index.html
  music_games/index.html
  other/index.html
  sitemap.xml
  zh_cn/index.html
  无聊闲话.html
Labels: bug, DEV-已完成, DEV-开发分支合并, DEV-测试通过, 优化

#96 添加更多歌单
  zh_cn/js/SongList.js
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#98 New Blog
  Articles/Blogs.html
  Articles/index.html
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#105 feat: ✨优化议题模板
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/preference_adjective.yml
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#108 玩音游玩的
  music_games/games/Milthm/index.html
  music_games/photos/Milthm/[Algebra(PC)]-0980577-S.png
  music_games/photos/Milthm/[Bio-Engineering(PC)]-0983781-S.png
  music_games/photos/Milthm/[Bio-Engineering(PC)]-0987876-S.png
  music_games/photos/Milthm/[Fly To Meteor feat.兔柒 (Milthm Edit)(PC)]-0935010-A.png
  music_games/photos/Milthm/[INFP.mp3(PC)]-0980060-S.png
  music_games/photos/Milthm/[Innocent white(PC)]-0900963-A.png
  music_games/photos/Milthm/[Moonflutter(PC)(CL)]-0898655-A.png
  music_games/photos/Milthm/[Moving On(PC)]-0972875-S.png
  music_games/photos/Milthm/[Threat - Sky Islands(PC)]-0947329-S.png
  music_games/photos/Milthm/[Threat - Sky Islands(PC)]-0959714-S.png
  music_games/photos/Milthm/[Threat - Superstructure(PC)]-0890561-A.png
  music_games/photos/Milthm/[WATER(PC)]-0965112-S.png
  music_games/photos/Milthm/[WATER(PC)]-0976470-S.png
  music_games/photos/Milthm/[WATER(PC)]-0987859-S.png
  music_games/photos/Milthm/[イコラト(PC)]-0960509-S.png
  music_games/photos/Milthm/[命日(PC)(CL)]-0877975-A.png
  music_games/photos/Milthm/[命日(PC)]-0981980-S.png
  music_games/photos/Milthm/[樱落繁花(PC)]-0957997-S.png
  music_games/photos/Milthm/[雨女(PC)(CL)]-0966657-S.png
  music_games/photos/Milthm/[雨女(PC)]-0970868-S.png
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#117 fix: 更正 APlayer 参数
  music_games/games/Milthm/index.html
  music_games/games/Phigros/index.html
  music_games/photos/Milthm/[Aconsma]-0955956-S.png
  music_games/photos/Milthm/[Contrasty Angeles(CL)]-0946959-S.png
  music_games/photos/Milthm/[Contrasty Angeles]-0967565-S.png
  music_games/photos/Milthm/[Fragment of Memories]-0972533-S.png
  music_games/photos/Milthm/[OverRain]-0978818-S.png
  music_games/photos/Milthm/[Regnaissance(CL)]-0964840-S.png
  music_games/photos/Milthm/[Regnaissance]-0976060-S.png
  music_games/photos/Milthm/[粗线条的雨]-0945368-S.png
  music_games/photos/Phigros/[ATHAZA (AT)]-0883717-A.png
  music_games/photos/Phigros/[Crush BETA]-0997421-Vp.png
  music_games/photos/Phigros/[Schadenfreude]-0985235-V.png
  music_games/photos/Phigros/[Spasmodic (AT)]-0890389-A.png
  music_games/photos/Phigros/[TECHNOPOLIS 2085 (AT)]-0915400-A.png
  music_games/photos/Phigros/[デリトリーバトル (AT)]-0932075-S.png
  music_games/photos/Phigros/[暗夜苏醒 (REANIMATE)]-0956838-S.png
  music_games/photos/Phigros/[暗夜苏醒 (REANIMATE)]-0957595-S.png
  music_games/photos/Phigros/[黄金之城 (GOLD TOWN)]-0922853-S.png
  zh_cn/js/SongList.js
Labels: DEV-开发分支合并, DEV-测试通过, 处理中

#119 修复一些已知问题
  Articles/Blogs.html
  Articles/探寻海丝起点-鲤城泉州.html
  GenshinImpact/index.html
  Interesting/duck_forever/index.html
  Interesting/sky/index.html
  Tools/Blabberizer.html
  Tools/Fufu_Tools/online_tools/实验性工具/水下音效/index.html
  Tools/Fufu_Tools/wiki/Dev/index.html
  Tools/Fufu_Tools/wiki/error/index.html
  Tools/chinese_git/Spare-Download/info.json
  Tools/chinese_git/index.html
  minecraft/index.html
  minecraft/promotion/fake.html
  minecraft/promotion/index.html
  minecraft/promotion/oak_island/index.html
  minecraft/promotion/oak_island/oak_island_farm.html
  music_games/index.html
  other/Luna-Grace/index.html
  zh_cn/css/optimize.css
  zh_cn/index.html
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 优化

#122 feat🚀: 对于手机测试的控制台页面
  zh_cn/debug.html
Labels: DEV-开发分支合并, DEV-未经测试

#124 更新芙芙工具箱依赖文件
  Tools/Fufu_Tools/wiki/files/text/requirements.txt
  Tools/Fufu_Tools/wiki/index.html
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-未经测试

#125 更新 dependabot.yml
  .github/dependabot.yml
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#128 玩音游玩的
  music_games/games/Milthm/index.html
  music_games/games/Notanote/index.html
  music_games/games/Orzmic/index.html
  music_games/games/Phigros/index.html
  music_games/index.html
  music_games/photos/Milthm/[Fly To Meteor (Milthm Edit)]-0980323-S.png
  music_games/photos/Milthm/[Fly To Meteor feat.兔柒 (Milthm Edit)]-0966727-S.png
  music_games/photos/Milthm/[时落之雨]-0982590-S.png
  music_games/photos/Orzmic/[Le Porteur d'Ombre]-0957668-A.png
  music_games/photos/Orzmic/[Le Porteur d'Ombre]-0960502-A.png
  music_games/photos/Orzmic/[The Everlasting Rain (NORMAL)]-0991752-Sp.png
  music_games/photos/Orzmic/[The Everlasting Rain]-0958690-A.png
  music_games/photos/Phigros/[FULi AUTO BUSTER]-0996662-Vp.png
  music_games/photos/Phigros/[FULi AUTO BUSTER]-1000000-phi.png
  music_games/photos/Phigros/[Le temps perdu]-0986676-V.png
  music_games/photos/Phigros/[Le temps perdu]-1000000-phi.png
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并

#129 新歌
  zh_cn/js/SongList.js
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-未经测试, 其他

#130 fix: 修正 Sitemap 生成脚本
  .action_scripts/JavaScript/generate-sitemap.mjs
  sitemap.xml
Labels: bug, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, DEV-需要注意

#132 feat: 为生成的 Sitemap 添加 <lastmod>
  .action_scripts/JavaScript/generate-sitemap.mjs
  .github/workflows/generate-sitemap.yml
  Tools/Fufu_Tools/wiki/Dev/index.html
  Tools/Fufu_Tools/wiki/index.html
  Tools/Fufu_Tools/wiki/常见问题QandA/主程序/index.html
  Tools/Fufu_Tools/wiki/常见问题QandA/小工具/index.html
  Tools/Fufu_Tools/wiki/通用/index.html
  sitemap.xml
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 新功能

#142 玩音游玩的
  music_games/games/Milthm/index.html
  music_games/games/Orzmic/index.html
  music_games/games/Phigros/index.html
  music_games/photos/Milthm/[Algebra(PC)]-0980577-S.png
  music_games/photos/Milthm/[Algebra(PC)]-0987237-S.png
  music_games/photos/Milthm/[Contrasty Angeles(PC)(CL)]-0910357-A.png
  music_games/photos/Milthm/[Fly To Meteor (Milthm Edit)(PC)]-0979555-S.png
  music_games/photos/Milthm/[Fly To Meteor (Milthm Edit)(PC)]-0998433-S.png
  music_games/photos/Milthm/[Fly To Meteor feat.兔柒 (Milthm Edit)(PC)(CL)]-0973374-S.png
  music_games/photos/Milthm/[Fly To Meteor feat.兔柒 (Milthm Edit)(PC)]-0935010-A.png
  music_games/photos/Milthm/[INFP.mp3(PC)]-0980060-S.png
  music_games/photos/Milthm/[INFP.mp3(PC)]-0990346-S.png
  music_games/photos/Milthm/[Innocent white(PC)]-0912815-A.png
  music_games/photos/Milthm/[Innocent white(PC)]-0936112-A.png
  music_games/photos/Milthm/[Moonflutter(PC)(CL)]-0898655-A.png
  music_games/photos/Milthm/[Moonflutter(PC)(CL)]-0919464-A.png
  music_games/photos/Milthm/[Moonflutter(PC)]-0953327-S.png
  music_games/photos/Milthm/[Moonflutter(PC)]-0979772-S.png
  music_games/photos/Milthm/[Regnaissance(PC)(CL)]-0945331-S.png
  music_games/photos/Milthm/[Words(PC)]-1001397-Sp.png
  music_games/photos/Milthm/[slic.hertz 井GdbG(PC)]-0968799-S.png
  music_games/photos/Milthm/[ネオン色のまち feat. Mai(PC)]-0990996-S.png
  music_games/photos/Milthm/[ネオン色のまち feat. Mai(PC)]-0992948-Sp.png
  music_games/photos/Milthm/[暮予星光(PC)]-1000622-Sp.png
  music_games/photos/Milthm/[烁雨(PC)]-0983195-S.png
  music_games/photos/Milthm/[烁雨(PC)]-1003481-Sp.png
  music_games/photos/Milthm/[白虎蓮華(PC)]-0959427-S.png
  music_games/photos/Milthm/[雨之城(PC)]-1005601-Spp.png
  music_games/photos/Orzmic/[When The Light Flows]-0988877-S.png
  music_games/photos/Orzmic/[cybernetic blazar]-0957926-A.png
  music_games/photos/Phigros/[Der Richter]-0921732-S.png
  music_games/photos/Phigros/[Der Richter]-0921906-S.png
Labels: DEV-已启用自动合并, DEV-开发分支合并

#141 translate: 为其他语言的 404 页面添加管理员信息
  en/404.html
  jp/404.html
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 翻訳

#147 [Milthm] 20241128/29 - Replace and add
  .github/workflows/generate-sitemap.yml
  music_games/games/Milthm/index.html
  music_games/photos/Milthm/[Aconsma(PC)]-0939909-S.png
  music_games/photos/Milthm/[Aconsma(PC)]-0981970-S.png
  music_games/photos/Milthm/[Agnostic(PC)]-0975135-S.png
  music_games/photos/Milthm/[Agnostic(PC)]-0984484-S.png
  music_games/photos/Milthm/[Dogbite(PC)]-0974986-S.png
  music_games/photos/Milthm/[Dogbite(PC)]-0992142-S.png
  music_games/photos/Milthm/[Fly To Meteor (Milthm Edit)(PC)]-0998433-S.png
  music_games/photos/Milthm/[Fly To Meteor (Milthm Edit)(PC)]-1001903-Sp.png
  music_games/photos/Milthm/[Innocent white(PC)]-0936112-A.png
  music_games/photos/Milthm/[Innocent white(PC)]-0941834-S.png
  music_games/photos/Milthm/[Psyched Fevereiro(PC)]-0959325-S.png
  music_games/photos/Milthm/[Psyched Fevereiro(PC)]-0984409-S.png
  music_games/photos/Milthm/[Regnaissance(PC)]-0991348-S.png
  music_games/photos/Milthm/[WATER(PC)]-0987859-S.png
  music_games/photos/Milthm/[WATER(PC)]-0991952-S.png
  music_games/photos/Milthm/[cybernetic blazar(PC)]-0990692-Sp.png
  music_games/photos/Milthm/[cybernetic blazar(PC)]-1000239-Sp.png
  music_games/photos/Milthm/[参宿四~Betelgeuse~(PC)]-0967594-S.png
  music_games/photos/Milthm/[暮予星光(PC)]-1000622-Sp.png
  music_games/photos/Milthm/[暮予星光(PC)]-1005206-Spp.png
  music_games/photos/Milthm/[白虎蓮華(PC)]-0959427-S.png
  music_games/photos/Milthm/[白虎蓮華(PC)]-0975506-S.png
  music_games/photos/Milthm/[雨女(PC)]-0970868-S.png
  music_games/photos/Milthm/[雨女(PC)]-0994767-S.png
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#150 [Milthm] 20241129 - Replace and add
  music_games/games/Milthm/index.html
  music_games/photos/Milthm/[Dogbite(PC)]-0992142-S.png
  music_games/photos/Milthm/[Dogbite(PC)]-0993552-S.png
  music_games/photos/Milthm/[Fly To Meteor (Milthm Edit)(PC)]-1001903-Sp.png
  music_games/photos/Milthm/[Fly To Meteor (Milthm Edit)(PC)]-1006201-Spp.png
  music_games/photos/Milthm/[HYPER MEMORIES(PC)]-0968933-S.png
  music_games/photos/Milthm/[OverRain(PC)]-0968921-S.png
  music_games/photos/Milthm/[OverRain(PC)]-0992245-S.png
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过
