Repository DuckDuckStudio/yazicbs.github.io, pull requests merged in 2024-12, with the labels that each got.

#153 统一显示
  music_games/games/Milthm/index.html
  music_games/games/Orzmic/index.html
  music_games/photos/Milthm/[Blueface]-0955577-S.png
  music_games/photos/Milthm/[Jump out]-0987469-Sp.png
  music_games/photos/Milthm/[Moonflutter]-0979360-S.png
  music_games/photos/Milthm/[Moving On]-0982912-Sp.png
  music_games/photos/Milthm/[イコラト]-0952527-S.png
  music_games/photos/Milthm/[命日]-0969779-S.png
  music_games/photos/Milthm/[雨女]-0988201-S.png
  music_games/photos/Orzmic/[Access Denied]-0982269-S.png
  music_games/photos/Orzmic/[Bad Gateway]-0987593-S.png
  music_games/photos/Orzmic/[核心共振]-0951298-A.png
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并

#157 坏了，崩坏三还在追我
  pictures/福.png
  zh_cn/js/SongList.js
Labels: DEV-开发分支合并, DEV-测试通过

#156 我玩音游怎么了
  music_games/games/Milthm/index.html
  music_games/games/Orzmic/index.html
  music_games/photos/Milthm/[Algebra(PC)]-0987237-S.png
  music_games/photos/Milthm/[Algebra(PC)]-0994421-S.png
  music_games/photos/Milthm/[Contrasty Angeles(PC)(CL)]-0910357-A.png
  music_games/photos/Milthm/[Contrasty Angeles(PC)(CL)]-0911406-A.png
  music_games/photos/Milthm/[Dogbite(PC)]-0993552-S.png
  music_games/photos/Milthm/[Dogbite(PC)]-1001006-Sp.png
  music_games/photos/Milthm/[Fly To Meteor feat.兔柒 (Milthm Edit)(PC)(CL)]-0973374-S.png
  music_games/photos/Milthm/[Fly To Meteor feat.兔柒 (Milthm Edit)(PC)(CL)]-0976705-S.png
  music_games/photos/Milthm/[Fragment of Memories(PC)]-0950789-S.png
  music_games/photos/Milthm/[Fragment of Memories(PC)]-0980693-S.png
  music_games/photos/Milthm/[INFP.mp3(PC)]-0990346-S.png
  music_games/photos/Milthm/[INFP.mp3(PC)]-0998703-Sp.png
  music_games/photos/Milthm/[Innocent white(PC)]-0941834-S.png
  music_games/photos/Milthm/[Innocent white(PC)]-0954254-S.png
  music_games/photos/Milthm/[Moonflutter(PC)]-0979772-S.png
  music_games/photos/Milthm/[Moonflutter(PC)]-0993243-S.png
  music_games/photos/Milthm/[Oniichan(PC)]-0922861-A.png
  music_games/photos/Milthm/[Oniichan(PC)]-0969349-S.png
  music_games/photos/Milthm/[Regnaissance(PC)(CL)]-0945331-S.png
  music_games/photos/Milthm/[Regnaissance(PC)(CL)]-0969045-S.png
  music_games/photos/Milthm/[WATER(PC)]-0991952-S.png
  music_games/photos/Milthm/[WATER(PC)]-0996554-S.png
  music_games/photos/Milthm/[slic.hertz 井GdbG(PC)]-0968799-S.png
  music_games/photos/Milthm/[slic.hertz 井GdbG(PC)]-0973718-S.png
  music_games/photos/Milthm/[仮想明日(PC)]-0984511-Sp.png
  music_games/photos/Milthm/[命日(PC)(CL)]-0877975-A.png
  music_games/photos/Milthm/[命日(PC)(CL)]-0917694-A.png
  music_games/photos/Milthm/[时落之雨(PC)]-0966836-S.png
  music_games/photos/Milthm/[时落之雨(PC)]-0990357-Sp.png
  music_games/photos/Milthm/[樱落繁花(PC)]-0957997-S.png
  music_games/photos/Milthm/[樱落繁花(PC)]-0984010-S.png
  music_games/photos/Milthm/[烁雨(PC)]-1003481-Sp.png
  music_games/photos/Milthm/[烁雨(PC)]-1006603-Spp.png
  music_games/photos/Milthm/[花月(PC)]-0981864-S.png
  music_games/photos/Milthm/[花月(PC)]-0998396-S.png
  music_games/photos/Orzmic/[FORBIDDEN MAGICKA]-0986167-S.png
  music_games/photos/Orzmic/[Lights in the Painting]-0987180-S.png
  music_games/photos/Orzmic/[cybernetic blazar]-0957926-A.png
  music_games/photos/Orzmic/[cybernetic blazar]-0962943-A.png
  pictures/福.png
  zh_cn/css/灯笼.css
  zh_cn/debug.html
  zh_cn/index.html
  zh_cn/js/Festivals.js
  zh_cn/js/SongList.js
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#161 docs: 新增芙芙工具箱工具介绍文档
  Tools/Fufu_Tools/photos/爬取网站搜索结果.png
  Tools/Fufu_Tools/photos/系统时间显示.png
  Tools/Fufu_Tools/wiki/各个工具文档/index.html
  Tools/Fufu_Tools/wiki/各个工具文档/颜色代码展示/index.html
  zh_cn/js/SongList.js
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过, 文档
