Repository DuckDuckStudio/yazicbs.github.io, pull requests merged in 2024-09, with the labels that each got.

#47 Update link_checker.py
  .action_scripts/link_checker.py
Labels: DEV-开发分支合并, 内部任务

#49 docs: 更新芙芙工具箱文档
  Tools/Fufu_Tools/index.html
  Tools/Fufu_Tools/versions/index.html
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 文档, 项目

#48 标语: 做√の自己
  .action_scripts/link_checker.py
  README.md
  font/做根号的自己.png
  zh_cn/index.html
  zh_cn/js/Festivals.js
  zh_cn/js/PersonalCount.js
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过

#46 docs: 添加芙芙工具箱错误信息文档
  .action_scripts/link_checker.py
  .github/workflows/check_url_visit.yml
  Tools/Fufu_Tools/wiki/error/index.html
  Tools/Fufu_Tools/wiki/index.html
  Tools/Fufu_Tools/wiki/通用/index.html
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-需要注意, 文档, 项目, 清理工作区

#52 Auto: 修改建议
  en/404.html
  jp/404.html
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过

#51 mg&pref: 优化404页面与音游记录页面
  404.html
  en/404.html
  jp/404.html
  music_games/games/MuseDash/index.html
  music_games/games/Phigros/index.html
  music_games/photos/MuseDash/[Brain Power]-304922-Sp.png
  music_games/photos/MuseDash/[Brain Power]-306246-Sp.png
  music_games/photos/MuseDash/[無人区-Vacuum Track井ADD8E6-]-369163-S.png
Labels: DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 优化

#53 Update branch
  404.html
  Articles/Blogs.html
  Articles/index.html
  Articles/personal-index.html
  Articles/photos/2024091801.png
  Articles/photos/2024091802.png
  Articles/photos/2024091803.png
  Articles/photos/2024091804.png
  Interesting/vacation_countdown/计算-时.js
  Tools/Fufu_Tools/wiki/error/index.html
  en/404.html
  jp/404.html
  music_games/games/MuseDash/index.html
  music_games/games/Phigros/index.html
  music_games/photos/MuseDash/[Brain Power]-304922-Sp.png
  music_games/photos/MuseDash/[Brain Power]-306246-Sp.png
  music_games/photos/MuseDash/[無人区-Vacuum Track井ADD8E6-]-369163-S.png
  sitemap.xml
  zh_cn/index.html
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过, 内部任务

#55 更新芙芙工具箱开发工具包最新预览版
  .gitignore
  Tools/Fufu_Tools/index.html
  music_games/games/Arcaea/index.html
  music_games/games/Orzmic/index.html
  music_games/games/Phigros/index.html
  music_games/photos/Arcaea/[Grimheart]-09870525-EX-TC.png
  music_games/photos/Orzmic/[Hello Halloween]-1000000-O.png
  music_games/photos/Phigros/[ATHAZA(AT)]-0880871-A.png
  music_games/photos/Phigros/[ATHAZA]-0927441-S.png
  music_games/photos/Phigros/[Chronomia]-0960534-V.png
  music_games/photos/Phigros/[Der Richter]-0910170-A.png
  music_games/photos/Phigros/[Grimheart]-0973198-V.png
  music_games/photos/Phigros/[NightTheater]-1000000-phi.png
  music_games/photos/Phigros/[Ramification]-0990533-Vp.png
  music_games/photos/Phigros/[デリトリーバトル]-1000000-phi.png
  music_games/photos/Phigros/[君往何处(Quo Vadis)]-0996968-Vp.png
  music_games/photos/Phigros/[暗夜苏醒(REANIMATE)]-0914295-A.png
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过, 内部任务, 文档, 项目
