Repository DuckDuckStudio/yazicbs.github.io, pull requests merged in 2024-08, with the labels that each got.

#31 [feat&pref] 添加JS输出范围&优化地区显示
  zh_cn/index.html
  zh_cn/js/PersonalCount.js
  zh_cn/js/SongList.js
  zh_cn/js/games/guess_number.js
  zh_cn/js/games/simplified/guess_number.js
  zh_cn/js/js范围定义.md
Labels: DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 优化, 新功能, 网站

#32 更新芙芙工具箱主页以适配最新独立开发工具包版本以及更新其开源许可文件总览
  Tools/Fufu_Tools/index.html
Labels: DEV-PR中修复, DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 优化, 待发布, 网站

#34 fix:修复地区识别出错 (#33)
  zh_cn/index.html
Labels: bug, DEV-PR中修复, DEV-已完成, DEV-未经测试

#35 更新芙芙工具箱版本
  Tools/Fufu_Tools/index.html
Labels: DEV-PR中修复, DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 待发布, 文档, 网站

#37 [TEST] 检查代码中的本地路径
  .action_scripts/check-local-paths.js
  .github/workflows/check-local-paths.yml
  .gitignore
Labels: DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 优化

#38 今日份记录
  minecraft/index.html
  minecraft/photos/Arc-光与对立.png
  minecraft/photos/大冰湖日落.png
  music_games/games/Orzmic/index.html
  music_games/photos/Orzmic/[Eligos]-0994101-S.png
  music_games/photos/Orzmic/[Falsely]-0983032-S.png
  music_games/photos/Orzmic/[Finale Destination]-0995707-S.png
  music_games/photos/Orzmic/[Myth(vip)]-0986259-S.png
  music_games/photos/Orzmic/[iΓ-fǝRric]-0972314-A.png
Labels: DEV-已完成, DEV-开发分支合并, DEV-本地测试通过

#39 feat: 自动检查链接有效性
  .action_scripts/link_checker.py
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check_url_visit.yml
  Articles/personal-index.html
  Tools/Fufu_Tools/wiki/index.html
  Tools/Fufu_Tools/wiki/通用/index.html
  minecraft/promotion/oak_island/oak_island_farm.html
  music_games/games/Other/index.html
  new_page/css/old_page_style.css
  new_page/index.html
  new_page/photos/music_list.png
  new_page/photos/鸭鸭跑酷.png
  zh_cn/index.html
  无聊闲话.html
Labels: DEV-开发分支合并, DEV-本地测试通过, 优化, 新功能

#40 Auto sync branch change(s)
  .action_scripts/check-local-paths.js
  .action_scripts/link_checker.py
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-local-paths.yml
  .github/workflows/check_url_visit.yml
  .gitignore
  Articles/personal-index.html
  Tools/Fufu_Tools/wiki/index.html
  Tools/Fufu_Tools/wiki/通用/index.html
  minecraft/index.html
  minecraft/photos/Arc-光与对立.png
  minecraft/photos/大冰湖日落.png
  minecraft/promotion/oak_island/oak_island_farm.html
  music_games/games/Orzmic/index.html
  music_games/games/Other/index.html
  music_games/photos/Orzmic/[Eligos]-0994101-S.png
  music_games/photos/Orzmic/[Falsely]-0983032-S.png
  music_games/photos/Orzmic/[Finale Destination]-0995707-S.png
  music_games/photos/Orzmic/[Myth(vip)]-0986259-S.png
  music_games/photos/Orzmic/[iΓ-fǝRric]-0972314-A.png
  new_page/css/old_page_style.css
  new_page/index.html
  new_page/photos/music_list.png
  new_page/photos/鸭鸭跑酷.png
  zh_cn/index.html
  无聊闲话.html
Labels: DEV-开发分支合并, 内部任务

#41 🌟ˋ( ° ▽、° ) 一些小的优化
  Articles/Blogs.html
  music_games/games/MuseDash/index.html
  music_games/photos/MuseDash/[Cyaegha]-334633-Sp.png
  music_games/photos/MuseDash/[Cyaegha]-336504-Sp.png
  music_games/photos/MuseDash/[ManiFesto：]-330791-Sp.png
  music_games/photos/MuseDash/[ManiFesto：]-342355-Sp.png
  music_games/photos/MuseDash/[Operation Blade]-239971-Sp.png
  music_games/photos/MuseDash/[Operation Blade]-241263-Sp.png
  music_games/photos/MuseDash/[恋のMoonlight]-234752-Sp.png
  zh_cn/index.html
Labels: bug, DEV-已完成, DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 优化

#42 feat: 404ページに日本語を追加しました
  404.html
  en/404.html
  jp/404.html
Labels: DEV-自动检查错误, DEV-开发分支合并, DEV-测试通过, 翻訳
