Repository DuckDuckStudio/yazicbs.github.io, pull requests merged in 2025-01, with the labels that each got.

#166 更新芙芙工具箱开发工具包预览版版本链接至2025.01.02.2300
  Tools/Fufu_Tools/index.html
Labels: DEV-已完成, DEV-开发分支合并, DEV-测试通过, 项目

#168 chore(license): 更新芙芙工具箱许可文件信息
  Tools/Fufu_Tools/index.html
Labels: DEV-开发分支合并, DEV-测试通过, 内部任务, 项目

#174 [Auto] [Milthm] 20250116 - Update
  .gitignore
  music_games/games/Milthm/index.html
  music_games/photos/Milthm/[Agnostic(PC)]-0984484-S.png
  music_games/photos/Milthm/[Agnostic(PC)]-0996864-S.png
  music_games/photos/Milthm/[Algebra(PC)]-0994421-S.png
  music_games/photos/Milthm/[Algebra(PC)]-0998823-Sp.png
  music_games/photos/Milthm/[Bio-Engineering(PC)]-0987876-S.png
  music_games/photos/Milthm/[Bio-Engineering(PC)]-0996723-Sp.png
  music_games/photos/Milthm/[Blueface(PC)]-0988547-Sp.png
  music_games/photos/Milthm/[Broken Conviction(PC)(CL)]-0948195-S.png
  music_games/photos/Milthm/[Broken Conviction(PC)]-0954422-S.png
  music_games/photos/Milthm/[Contrasty Angeles(PC)(CL)]-0911406-A.png
  music_games/photos/Milthm/[Contrasty Angeles(PC)(CL)]-0922062-A.png
  music_games/photos/Milthm/[Contrasty Angeles(PC)]-0940067-S.png
  music_games/photos/Milthm/[Contrasty Angeles(PC)]-96980185-S.png
  music_games/photos/Milthm/[Dogbite(PC)(SP)]-0886509-A.png
  music_games/photos/Milthm/[Dogbite(PC)(SP)]-0929365-A.png
  music_games/photos/Milthm/[Fragment of Memories(PC)]-0980693-S.png
  music_games/photos/Milthm/[Fragment of Memories(PC)]-0993590-Sp.png
  music_games/photos/Milthm/[Future Unbound (Game Edit)(PC)]-0989365-Sp.png
  music_games/photos/Milthm/[Hikari(PC)]-0974433-S.png
  music_games/photos/Milthm/[IN(PC)]-0983734-Sp.png
  music_games/photos/Milthm/[Innocent white(PC)]-0954254-S.png
  music_games/photos/Milthm/[Innocent white(PC)]-0964694-S.png
  music_games/photos/Milthm/[Jump out(PC)]-1002418-Spp.png
  music_games/photos/Milthm/[Moonflutter(PC)]-0993243-S.png
  music_games/photos/Milthm/[Moonflutter(PC)]-0997965-Sp.png
  music_games/photos/Milthm/[OverRain(PC)]-0992245-S.png
  music_games/photos/Milthm/[OverRain(PC)]-1001154-S.png
  music_games/photos/Milthm/[Rainbow Flavor(PC)]-0996374-Sp.png
  music_games/photos/Milthm/[Regnaissance(PC)]-0991348-S.png
  music_games/photos/Milthm/[Regnaissance(PC)]-0994447-S.png
  music_games/photos/Milthm/[Threat - Superstructure(PC)]-0890561-A.png
  music_games/photos/Milthm/[Threat - Superstructure(PC)]-0964226-S.png
  music_games/photos/Milthm/[Words(PC)]-0994962-Sp.png
  music_games/photos/Milthm/[Words(PC)]-1001397-Sp.png
  music_games/photos/Milthm/[Words(PC)]-1002021-Spp.png
  music_games/photos/Milthm/[cybernetic blazar(PC)]-0998230-Sp.png
  music_games/photos/Milthm/[cybernetic blazar(PC)]-1000239-Sp.png
  music_games/photos/Milthm/[slic.hertz 井GdbG(PC)]-0973718-S.png
  music_games/photos/Milthm/[slic.hertz 井GdbG(PC)]-0978127-S.png
  music_games/photos/Milthm/[サイクルの欠片(PC)]-0999856-Sp.png
  music_games/photos/Milthm/[命日(PC)]-0981980-S.png
  music_games/photos/Milthm/[命日(PC)]-0988469-Sp.png
  music_games/photos/Milthm/[夜風(PC)]-0981423-S.png
  music_games/photos/Milthm/[樱落繁花(PC)]-0984010-S.png
  music_games/photos/Milthm/[樱落繁花(PC)]-0987319-S.png
  music_games/photos/Milthm/[粗线条的雨(PC)]-0984180-S.png
  music_games/photos/Milthm/[粗线条的雨(PC)]-0994480-Sp.png
  music_games/photos/Milthm/[驟雨の狭間(PC)]-0944924-S.png
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 工作流

#180 chore(fft-docs): Bump version to v1.3.6
  Tools/Fufu_Tools/index.html
  sitemap.xml
Labels: DEV-已启用自动合并, DEV-开发分支合并, DEV-测试通过, 项目
