Repository DuckDuckStudio/yazicbs.github.io, pull requests merged in 2025-06, with the labels that each got.

#292 pref: 将你好【某地】的位置范围扩大到省 #291
  zh_cn/debug.html
  zh_cn/index.html
Labels: DEV-开发分支合并, DEV-测试通过, 优化

#296 fix(CodeQL): 修复一些 CodeQL 扫描错误
  .github/workflows/check-local-paths.yml
  .github/workflows/check_url_visit.yml
  .github/workflows/generate-sitemap.yml
  .github/workflows/handle_auto_merge_labels.yml
  404.html
  en/404.html
  jp/404.html
Labels: DEV-开发分支合并, DEV-测试通过

#295 chore(logs): 修改简化版猜数字 js 的警告等级为 log
  zh_cn/js/games/simplified/guess_number.js
Labels: DEV-测试通过, 优化
